### ISSUE TITLE
Improperly formatted json data on Minion proposals

### ISSUE THREAD

**Issue by auryn-macmillan** [odyssy-automaton/pokemol-web#1036]
![image](https://user-images.githubusercontent.com/8453294/115418171-469a1900-a1c7-11eb-8d46-424d29faaa51.png)

When creating a minion proposal with a hex encoded transaction, the json data of the description does not seem to be properly formatted.

[Here is an example proposal](https://app.daohaus.club/dao/0x64/0x041b08c559d2f2165d7f0de6a278c535786ecdd1/proposals/2)'

**Comment by jordanlesich** [comment]
This was happening because the minion form wasn't saving a title for the proposal. 

For all new proposals, this issue should be fixed. Unfortunately, because this data is saved on chain, older proposals will still display that fallback message. 

I'll close this for now, and if we see any new proposals creating the same message, we can open it back up.
