### ISSUE TITLE
Bug: Can't edit option to hide proposal button from non-members after setup of Spam Filter Boost

### ISSUE THREAD

**Issue by thebadcc** [odyssy-automaton/pokemol-web#1641]
Once edited, the Proposal Anti-Span Boost no longer provides the ability to hide the "New Proposal" button for non-members.

**Comment by plor** [comment]
**Describe the bug**
The option to hide "New Proposal" button from non-members is only available at boost setup, can't change it in boost settings.

**To Reproduce**
Steps to reproduce the behavior:
1. Setup anti-spam boost (or use DAO with it already set up)
2. Go To "Boosts" > "Proposal Anti-Spam" > "Settings"
3. Click on "Edit"
4. Hide new proposal option is missing

**Expected behavior**

This option that is available on setup should be able to be changed. See setup screenshot.

**Actual behavior**

This option is missing, locking in whatever choice was made at setup.

**Screenshots**

![Screenshot from 2022-04-28 19-16-33](https://user-images.githubusercontent.com/408660/165867909-e82e3a01-9072-4932-bdb2-d83837da598f.png)

![Screenshot from 2022-04-28 19-18-29](https://user-images.githubusercontent.com/408660/165867922-33d2e36c-316f-47b5-acde-0f5710622cc7.png)

**Application area**

Where in the app is this happening?
- Integration or Boost

**Comment by brossetti1** [comment]
fixed by https://github.com/HausDAO/daohaus-app/pull/1838
