### ISSUE TITLE
Bug: Minion Proposal Filter on proposal list is not working

### ISSUE THREAD

**Issue by skuhlmann** [odyssy-automaton/pokemol-web#1781]

**Comment by plor** [comment]
**Describe the bug**
On proposal list, when selecting "Minion Proposals" no proposals are returned

**To Reproduce**
Steps to reproduce the behavior:
1. Go to DAO that has minion proposals (or create one)
2. Go to Proposals
3. Click on "Filter By"
4. Scroll down to "Minion Proposals"
5. See number results "(0)" in filter text and "No Proposals Here Yet" in view area

**Expected behavior**

Number of minion proposals made should display and proposal views should be displayed in list

**Actual behavior**

Filter is not picking up on minion proposals, none returned.

**Screenshots**

![image](https://user-images.githubusercontent.com/408660/165829356-22009f97-680e-4304-831e-d31276632bf9.png)

**Application area**

Where in the app is this happening?
- FrontEnd (please include route/section if possible)
  - Proposals
- Subgraph (unsure)
- API (unsure)
- Integration or Boost
  - Could be issue with minion versioning?

**Comment by brossetti1** [comment]
fixed by https://github.com/HausDAO/daohaus-app/pull/1839
