### ISSUE TITLE
Bug: Hub "Edit 3Box Profile" links to self.id

### ISSUE THREAD

**Issue by plor** [odyssy-automaton/pokemol-web#1871]
**Describe the bug**
The button to edit 3box profile links to the wrong place

**To Reproduce**
1. Go to Hub
2. Click on "Edit 3Box Profile"
3. See that you are directed to self.id

**Expected behavior**

Member profile update flow is presented to user clicking on button.

**Actual behavior**

Linked to self.id website

**Screenshots**
![](https://cdn.discordapp.com/attachments/899436946143723521/980529776513122304/profile.png)

**Application area**

Where in the app is this happening?
- FrontEnd (please include route/section if possible)

**Additional context**

From @Keating
> For V2 can remove or change where edit 3Box profile redirects to? It should redirect to our member profile update flow rather than self.id https://cdn.discordapp.com/attachments/899436946143723521/980529776513122304/profile.png

# Detials

<img width="695" alt="Screen Shot 2022-07-02 at 3 10 39 PM" src="https://user-images.githubusercontent.com/5998100/177016333-ed5f523d-f63e-4f75-ab7a-7af6e3e39161.png">
<img width="1195" alt="Screen Shot 2022-07-02 at 3 10 54 PM" src="https://user-images.githubusercontent.com/5998100/177016336-4510565e-aeff-41dd-bcbf-18337bc98b0d.png">
<img width="634" alt="Screen Shot 2022-07-02 at 3 11 07 PM" src="https://user-images.githubusercontent.com/5998100/177016337-ca2bb48f-d377-4782-b17c-f5d20abf5120.png">

**Comment by brossetti1** [comment]
@plor so looking at this one, this one is complicated by the fact that:

1) the `Edit 3 Box` button is on the Hub, where a user has not connected a dao yet.
2) The profile only shows when you have a dao selected, and the route requires a `${daoid}/profile/:userid`

ive looked over the code, and the only thing that the daoid does is display the daos tokens if you are connected to a dao -- that being said, its not not condusive to load it without a dao selected as it stands right now -- there are too many levels of components that hook into the dao currently, but this is not necessary in order to Edit the 3Box profile as nothing on that profile is dependent on the actual dao.

because of this we have 2 options:

1) extract the 3Box components out into its own component, and render it in the `baseRouter` as a standalone component without all the dao details that are embeded in the profile. (transactions, tokens, user voting history, etc.

2) move the Edit 3 Box button to the Dao header (that way the user can Edit 3 Box when they dig into a dao)

from a standard app standpoint, number 1 makes more sense, from a practicality standpoint, number 2 makes more sense. I would probably just suggest number 2 seeing as how we want to focus on v3 in the short term, so anyway to solve this fast is preferrrable. anyways, wondering which one you are thinking given all this?

I hae opened the [draft](https://github.com/HausDAO/daohaus-app/pull/1935) pr which shows the current changes its taken to get some sort of profile displaying without changing how the profile component works generally. There are still more levels to address and so its getting messsy (the approach attached to the draft is **neither** option 1 or 2 above. anyways, heres the current UI trying to render the current Profile (failing inside the ProfileMenu) -- (background is bugging because no dao is selected i imagine ¯\_(ツ)_/¯)

![Image](https://user-images.githubusercontent.com/5998100/176305821-6ba6484e-4ab6-4bfa-9107-0708826c4d31.png)

tagging @alexkeating as well after discussing with plor

**Comment by plor** [comment]
I think it is the flow within the profile that we need to capture, not necessarily go to the profile. I'm not sure if this is achievable without having the context of the profile, but we don't need the profile exactly.

**Comment by brossetti1** [comment]
@plor trying to extract just the 3Box form for the Hub view still has issues of nested dependencies with a connected dao. Even after spending time on this one trying to get the 3box form out into its own stepper modal, there are still issues nested where the components are dependent on a dao being selected.

This has to do with the `formBuilder` itself. In order to get this functioning, It would take making its own custom modal, totally doable, but I also feel like this is not a high enough priority that its worth investing that time into it.

the current state of this branch moves the 3Box edit button into the Dao Select layout using the `isDao` guard, it works fine there and does not take anymore effort. Another option would be to just remove the button altogether --- thoughts on this implementation vs removing it altogether?

(ive attached pictures to the story)

https://github.com/HausDAO/daohaus-app/pull/1935
