### ISSUE TITLE
Bug: WSOD on Proposal List Page due to bad minion action

### ISSUE THREAD

**Issue by skuhlmann** [odyssy-automaton/pokemol-web#1915]
# Details

Load this page to see the app crash
https://app.daohaus.club/dao/0x89/0xb307eae573fd0595ebda024eb57a22b5d3f0f63c/proposals

Looks to me like it's failing on calls to get minion actions in minionUtils.js

in function: `getMinionAction`

```
 const action = await minionContract.methods[actionName](proposalId).call();
```

this doesn't function call doesn't return. error screenshot attached.
![Image](https://user-images.githubusercontent.com/6923345/174611728-633ff9db-c1f9-4bee-a568-c0827f3477bc.png)

To me it looks like it's trying to call for proposal 5 and 7. I don't see the immediate issue with those though.

**Comment by plor** [comment]
Hoping you might be able to take this on @santteegt

**Comment by santteegt** [comment]
@skuhlmann a decoding error is being thrown because the Minion Safe used for the Superfluid proposal was [deployed using the new summoner contract](https://polygonscan.com/address/0xbdc05c8f8f133d5b1f81b5feb4d3fcf5d493849c#internaltx) but the ABI used to instantiate the contract is from the previous version.

- More specifically, the `actions` function signature differs between the two (different output vars)
- I think the new summoner should have a different minionType (e.g. SAFE MINION V1) so it'll be easier to distinguish which ABI to use. However, updating the factory would not fix the errors from vaults that were created during this time
- Can't just update the ABI as it will break previous vault deployments
- I could add a fallback to use the new ABI if the 1st call fails, but this approach will need to update all the places where the contract is called
- I'm happy to jump to a call to evaluate possible solutions

**Comment by plor** [comment]
Thanks @santteegt, this makes sense. We probably need to tack on some additional development on this to sort out these changes as it probably affects several operations on the minion safe.

**Comment by plor** [comment]
@skuhlmann should I make a task within the nomad milestone to separate out the new minion such that this ABI change is factored in?
