### ISSUE TITLE
messy eslint errors across v2

### ISSUE THREAD

**Issue by brossetti1** [odyssy-automaton/pokemol-web#1943]
**Describe the bug**
our eslint settings are out of whack and working in the project is spitting out lots of incorrect and unwanted errors.

currently commenting out `lines 42 - 44 in .eslintrc.js` removes any of the errors/warnings we're seeing. These 3 rules:

```
no-unused-vars: 'off' - actually need to explicitly set this to 'off'
react/jsx-uses-react
react/jsx-uses-vars
```

for more reference - https://discord.com/channels/709210493549674598/951186621397618708/991744816515915876

this gets ride of the slew of errors but also turns off some crucial eslint warnings. 

**Expected behavior**

We should turn them back on one at a time and correct the behavior across the app in this story

**Actual behavior**

lots of errors across the app due to breaking eslint rules or incorrect usage of eslint

**Screenshots**

![image](https://user-images.githubusercontent.com/5998100/176523085-5a56007d-caa6-42a6-80de-83f5f57e6c54.png)

**Comment by jordanlesich** [comment]
More behavior notes: 

- Errors seem to be happening everywhere we're importing JSX
- Warnings appears to be happening in files where we're importing JSX or React in .js files.
- Error will only surface when we open the file in the code editor. 
- The CI on deployment does not throw errors. Might be worth looking at the linting settings there. 

Other possibility: 
- We used to have a bug that caused errors because a version of Eslint inside a node_module would clash with our version.  Don't know what happened with this bug, (or the fix) but it could be a possible cause.
